;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="Discs",DevComment="")
+GameplayTagList=(Tag="Discs.Adrenaline",DevComment="")
+GameplayTagList=(Tag="Discs.DeathFromBelow",DevComment="")
+GameplayTagList=(Tag="Discs.ExpressShot",DevComment="")
+GameplayTagList=(Tag="Discs.Laser",DevComment="")
+GameplayTagList=(Tag="Discs.MetalSkin",DevComment="")
+GameplayTagList=(Tag="Discs.ReturnFire",DevComment="")
+GameplayTagList=(Tag="Discs.TrophyCollector",DevComment="")
+GameplayTagList=(Tag="Discs.Turret",DevComment="")
+GameplayTagList=(Tag="Discs.Vampire",DevComment="")
+GameplayTagList=(Tag="Discs.Weapons.Rifle",DevComment="")
+GameplayTagList=(Tag="Discs.Weapons.Shotgun",DevComment="")
+GameplayTagList=(Tag="Discs.Weapons.Smg",DevComment="")

